require 'dnssd'
require 'etc'
require 'ipaddr'
require 'set'

require File.dirname(__FILE__) + '/chatjour/application'
require File.dirname(__FILE__) + '/chatjour/status'
require File.dirname(__FILE__) + '/chatjour/buddy_list'
require File.dirname(__FILE__) + '/chatjour/messenger'
require File.dirname(__FILE__) + '/chatjour/controller'
